version: '3'
services:
  backend:
    build:
      context: ./backend # Path to the backend project directory
    # depends_on:
    #   - mysql
    ports:
      - 8000:8000
    container_name: backend

  frontend:
    build:
      context: ./frontend # Path to the frontend project directory
    ports:
      - 80:80
    container_name: frontend

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    ports:
      - 3308:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql

volumes:
  db_data:
